name: articles
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  retrofit: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ">=5.0.0 <6.0.0"
  build_runner: ">=2.3.0 <4.0.0"
  drift_dev: ^2.8.2
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  assets:
    - .env
