name: articles
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  retrofit: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ">=5.0.0 <6.0.0"
  build_runner: ">=2.3.0 <4.0.0"
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
